# Generated by Django 4.2.5 on 2023-10-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
