# Generated by Django 4.2.7 on 2024-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_booking_gender_alter_booking_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email_id',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
