# Generated by Django 4.2.7 on 2024-02-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_alter_booking_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
