# Generated by Django 4.2.7 on 2024-02-23 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_booking_seat_no_count_seat_map_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat_map',
            name='booked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
