# Generated by Django 4.2.7 on 2024-02-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_id', models.EmailField(max_length=254, null=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('total_price', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.schedule')),
                ('seatMap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.seat_map')),
            ],
        ),
    ]
