# Generated by Django 4.2.7 on 2024-03-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_address_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Toys', 'Toys'), ('KitchenItems', 'KitchenItems'), ('Stationary', 'Stationary')], max_length=200, null=True)),
                ('quantity', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
