# Generated by Django 4.2.7 on 2024-03-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Toys', 'Toys'), ('KitchenItems', 'KitchenItems'), ('Stationary', 'Stationary')], max_length=200, null=True)),
                ('brand', models.CharField(choices=[('QuillCraft', 'QuillCraft'), ('CreativeCanvas', 'CreativeCanvas'), ('CalinaQuetient', 'CalinaQuetient'), ('GastronomeGoods', 'GastronomeGoods'), ('HotWheelsHaven', 'Hot Wheels Haven')], max_length=50, null=True)),
                ('costPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveBigIntegerField(null=True)),
                ('minStockLevel', models.PositiveIntegerField(null=True)),
                ('maxStockLevel', models.PositiveIntegerField(null=True)),
                ('reorderPoint', models.PositiveIntegerField(null=True)),
                ('unitOfMeasurement', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='stock_images/')),
                ('description', models.TextField(null=True)),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gstin', models.CharField(max_length=15, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.supplier'),
        ),
    ]
