# Generated by Django 4.2.7 on 2024-03-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0028_supplier_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('1', 'Approve'), ('2', 'Pending'), ('3', 'Reject')], default='pending', max_length=20),
        ),
    ]
