# Generated by Django 4.2.7 on 2024-03-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_alter_stock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('total_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('contact_person_phone', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default='1', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
