# Generated by Django 4.2.7 on 2024-03-30 11:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0034_warehousetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUser',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_paid', models.CharField(choices=[('1', 'False'), ('2', 'True')], default='1', max_length=2)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.warehouse')),
                ('warehouse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.warehousetype')),
            ],
        ),
        migrations.CreateModel(
            name='StorageMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageNumber', models.CharField(max_length=50)),
                ('storage_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.storageuser')),
                ('warehouse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.warehousetype')),
            ],
        ),
    ]
