# Generated by Django 4.2.7 on 2024-04-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0036_storageuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageMapDup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storageNumber', models.CharField(max_length=50)),
                ('warehouse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.warehousetype')),
            ],
        ),
    ]
