# Generated by Django 4.2.7 on 2024-04-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0037_storagemapdup'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemapdup',
            name='selected_seats_display',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
