# Generated by Django 4.2.7 on 2024-04-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0038_storagemapdup_selected_seats_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagemapdup',
            name='storageNumber',
        ),
    ]
